### ISSUE TITLE
investigate bkernel's build.rs for easier cross-compiled libcore

### ISSUE THREAD

**Issue by steveklabnik** [intermezzOS/kernel#5]
@rasendubi has been doing interesting stuff:

https://github.com/rasendubi/bkernel/blob/master/build.rs

this might be a decent idea instead of the current "toss it in some directory" mess.

**Comment by phil-opp** [comment]
I just tried it and I think it doesn't work for dependencies since build scripts are only invoked for the main crate. It works in the linked repo because the same build script is executed for all dependencies (which we can't do for crates from `crates.io`).

An alternative solution could be cargo's support for [overriding dependencies](http://doc.crates.io/guide.html#overriding-dependencies). But unfortunately it only works for crates from `crates.io`.

**Comment by steveklabnik** [comment]
Ah, i see.
