### ISSUE TITLE
License

### ISSUE THREAD

**Issue by dpen2000** [intermezzOS/kernel#8]
What's the license for the code here?

**Comment by steveklabnik** [comment]
Since I derived this from @phil-opp 's code, which is apache2 licensed, it should also be apache2. https://github.com/phil-opp/blog_os/blob/printing_to_screen/LICENSE

Thanks for pointing this out, I'm really good about it usually, but forgot in this case. Phil, is it just apache2 or dual licensed?

**Comment by phil-opp** [comment]
Well, honestly I don't know much about licenses. What would be the advantages of dual licensing?

**Comment by steveklabnik** [comment]
Well, the only reason I ask is because Rust itself is dual licensed apache2/MIT, and so a lot of rust projects are as well.

The advantage is that if someone prefers one license over the other, they can create derived works under just the one they prefer. People do dual apache2/MIT because MIT is simpler, but has no patent clauses, and apache2 is more complex, but has protection for them. So some people don't like the extra complexity.

Really, it doesn't matter to me personally, I just want to make sure I do right by you, and anyone else who I happen to take a peek at their code :).

**Comment by phil-opp** [comment]
Ok thanks for the overview. I'm too tired to think about licenses right now but I will consider dual licensing (any drawbacks?).

**Comment by steveklabnik** [comment]
I've pushed up the Apache2 license. Thanks again @dpen2000 !

**Comment by phil-opp** [comment]
I've updated the license of [blog_os](https://github.com/phil-opp/blog_os). It's now apache2/MIT dual licensed.

**Comment by steveklabnik** [comment]
Cool, I will follow suit.
